### ISSUE TITLE
Const in constructor

### ISSUE THREAD

**Issue by rpharrigan211** [ifteda/CS4500-A1-Part2#11]
Could you change the String constructor so it takes in 'const char* c' instead of 'char* c'? Otherwise I get issues with certain comparisons.

**Comment by frankkulak** [comment]
@rpharrigan211 Our spec only includes methods/constructors that you are _required_ to implement, you are free to add anything else that you wish (including constructors). We will not be changing the spec since the assignment is due in nearly one hour.
