### ISSUE TITLE
Tests Wrong?

### ISSUE THREAD

**Issue by raacharya** [ifteda/CS4500-A1-Part2#3]
Hey guys, we were implementing our queue and running it on your tests, but we think there might be some issues. In test 2, you create two queues. You then add a and a1 to both of them. After that, you add b and c to them respectively. However, your tests say that peeking at them should return b and c. We believe that this is wrong for a queue, and that it should instead be a and a1, since they were added first, and therefore should be at the front of the queue. Additionally, when dequeuing, the function should return a and a1, not b and c. We think that your tests are actually testing a stack. Can you please fix them?

**Comment by ifteda** [comment]
Tests should now be fixed. Thanks for catching that! Let us know if you run into any more issues.
