### ISSUE TITLE
tests: use strcmp instead of == please

### ISSUE THREAD

**Issue by raacharya** [ifteda/CS4500-A1-Part2#4]
Hey guys,

So our implementation is working for pretty much all the tests except when you check for equality of the to_string function. The problem is that to_string returns a char* so == is not sufficient and the operator must be strcmp. Can you please either change these lines, or just remove the those tests altogether (since we are testing .equals anyways)? Either works. Thanks!

**Comment by ifteda** [comment]
Updated to_string() tests to use strcmp()!

**Comment by raacharya** [comment]
Thanks, but we don't see any changes to the tests. Did you push the changes?

**Comment by raacharya** [comment]
Sorry, there was just a delay in the update. Thanks!
