### ISSUE TITLE
Queue API seems to imply mixed-types?

### ISSUE THREAD

**Issue by rpharrigan211** [ifteda/CS4500-A1-Part2#6]
So the assignment dictates that we should be able to handle both Queues of Objects and Queues of Strings, but right now there seems to be no way for me to check if a Queue of solely Strings is valid. The only way currently is for Strings to be cast as Objects and added to an Object Queue, where they run the risk of existing with non-String objects. Might I suggest making a StringQueue class that extends Queue, such that we can create Queues that contain only Strings?

**Comment by ifteda** [comment]
Thank you for the suggestion, but we will not be going forward with this, as it will likely create obstacles for others implementing our API. Currently, we are not dictating that a Queue must be made up of a single type. In class today, the professors mentioned that this is a design choice for each group to make.
