### ISSUE TITLE
necessity of to_string()?

### ISSUE THREAD

**Issue by rpharrigan211** [ifteda/CS4500-A1-Part2#7]
The purpose of the to_string() function in your string.h API is ambiguous; being able to call to_string() on a string seems counterintuitive, regardless of what it outputs.

Looks like it is inherited from Object, and as such is also found in Queue, and I'm not sure what a proper purpose for this would be - it's mentioned in the documentation, but I'm not sure about its immediate practicality. The only way it's tested in test-queue.cpp is by comparing the outputted string to that of an unequal string, which would be functionally the same as just proving that they weren't equal using "equals()". Could you consider removing the to_string() function in its entirety if it doesn't interfere with the other teams working on this API? Or at the very least consider renaming it?

A lot of the class seems to be modeling their string.h class off of this Piazza post as well: https://piazza.com/class/k51bluky59n2jr?cid=345

EDIT: a word

**Comment by ifteda** [comment]
Removed to_string() method from Object, Queue, and String. Tests and README have also been updated to reflect this change.

**Comment by ifteda** [comment]
@raacharya This is to let you know that this change has been made. I know your team was working on getting the to_string() tests to pass. If you find that your team will not have enough time to have these changes reflected in your implementation, you should be able to simply reference the commit id you used (see Piazza post 333).
