### ISSUE TITLE
Memory Management

### ISSUE THREAD

**Issue by rohitppathak** [ifteda/CS4500-A1-Part2#8]
The test file should delete every Queue that it creates. In addition, who should be responsible for deleting Objects created in the test file and inserted into the Queue?

For example:
```
Queue* q1 = new Queue();
String* s1 = new String("hi");
q1->enqueue(s1);
delete q1; // these need to be added in the test file for sure

// should we have the following line??
delete s1;
```

Basically, if the last line should be in the test file, then the user needs to delete the objects created and inserted. If not, then the queue takes responsibility for deleting them. Which design did you have in mind? I would strongly recommend the former (the user deleting objects).

**Comment by ifteda** [comment]
We have updated the tests to delete Queues and their elements.
The design we have in mind is that deleting a Queue should not delete the Objects it contains, as there are cases for which this would result in a segfault.
